language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t flyeagle100/multi-docker-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true flyeagle100/multi-docker-test npm test

after_success:
  - docker build -t flyeagle100/multi-docker-client ./client
  - docker build -t flyeagle100/multi-docker-nginx ./nginx
  - docker build -t flyeagle100/multi-docker-server ./server
  - docker build -t flyeagle100/multi-docker-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push flyeagle100/multi-docker-client
  - docker push flyeagle100/multi-docker-nginx
  - docker push flyeagle100/multi-docker-server
  - docker push flyeagle100/multi-docker-worker
